project_name: null

projects_dir: benchmarking/Hardware/Renesas
project_dir: ${projects_dir}/${project_name}
user_config: benchmarking/models/automate/hardware_types/RenesasRX65N/configs/hardware_user_config.yaml
