# The script will iteratively populate the following parameter for each item in the TFLite_converter's output
model_base_dir: null
tflite_conversion_type: null

linkers_dir: linkers
user_config: edgemark/models/platforms/EI/configs/EI_converter_user_config.yaml
tflite_model_path: ${model_base_dir}/tflite/${tflite_conversion_type}/model.tflite
eqcheck_data_path: ${model_base_dir}/data/eqcheck_data.npz
data_templates_dir: edgemark/models/platforms/EI/EI_templates
ei_save_dir: ${model_base_dir}/ei/${tflite_conversion_type}
n_random_eqcheck_data: 10
