# The script will iteratively populate the following parameters for each item in the 'targets' collection
model_type: null
time_tag: null

target_models_dir: target_models
TF_base_dir: edgemark/models/platforms/TensorFlow
datasets_dir: edgemark/models/datasets
linkers_dir: linkers
model_path: ${TF_base_dir}/model_types/${model_type}/model.py

model_save_dir: saved_models/TensorFlow/${model_type}/${time_tag}
data_save_dir: ${model_save_dir}/data
TFLM_info_save_path: ${model_save_dir}/tflm/tflm_info.yaml

wandb_online: false
wandb_project_name: "EdgeMark"

train_models: true
evaluate_models: true
measure_execution_time: true

# epochs: 1                   # If specified, overrides the number of epochs in the model configuration

n_representative_data: 200    # This number of samples will be saved and later used for TFLite conversion
n_eqcheck_data: 10            # This number of samples will be saved and later used for equivalence check of model on PC and MCU
