model_type: "CNN"
convs_params: []
denses_params: [10, 10]
convs_dropout: 0.00
denses_dropout: 0.00
activation: "sigmoid"
use_batch_norm: False
epochs: 50
batch_size: 32
dataset:
  name: "randomset_regression"
  args:
    n_samples: 1000
    test_ratio: 0.2
    feature_shape: [1]
    random_seed: 42
random_seed: 42
