# The script will iteratively populate the following parameter for each item in the TFLite_converter's output
model_base_dir: null
tflite_conversion_type: null

linkers_dir: linkers
tflite_model_path: ${model_base_dir}/tflite/${tflite_conversion_type}/model.tflite
eqcheck_data_path: ${model_base_dir}/data/eqcheck_data.npz
tflm_info_path: ${model_base_dir}/tflm/tflm_info.yaml
tflm_templates_dir: benchmarking/models/platforms/TFLM/TFLM_templates
tflm_save_dir: ${model_base_dir}/tflm/${tflite_conversion_type}
