name: Run code quality checks

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  code_quality_check:
    name: Run code quality checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          python -m pip install -r requirements_test.txt

      - name: Run ruff
        run: |
          ruff check benchmarking

      # - name: Run mypy
      #   run: |
      #     mypy benchmarking --install-types --non-interactive
