model_type: "TinyMLPerf_AE"
load_pretrained_model: True
# denses_params: [128, 128, 128, 128, 8, 128, 128, 128]
# denses_dropout: 0.00
# activation: "relu"
# use_batch_norm: True
epochs: 0
batch_size: 512
dataset:
  name: "toyADMOS"
  args:
    n_mels: 128
    frames: 5
    n_fft: 1024
    hop_length: 512
    power: 2.0
    test_ratio: 0.1
    random_seed: 42
random_seed: 42
