model_type: "TinyMLPerf_MBNet"
load_pretrained_model: True
# num_filters: 8
# activation: "relu"
# use_batch_norm: True
epochs: 0
batch_size: 32
dataset:
  name: "vww"
  args:
    image_size: [96, 96]
    dataset_ratio: 0.1
    test_ratio: 0.1
    flat_features: False
    random_seed: 42
random_seed: 42
