model_type: "TinyMLPerf_ResNet"
load_pretrained_model: True
# num_filters: 16
# activation: "relu"
# use_batch_norm: True
epochs: 0
batch_size: 32
dataset:
  name: "cifar10"
  args:
    flat_features: False
random_seed: 42
